# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: acade_development
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres123' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: 5432

test:
  <<: *default
  database: acade_test
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres123' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL_PRODUCTION'] %>

cable:
  production:
    url: <%= ENV['DATABASE_URL_PRODUCTION'] %>
